# Generated by Django 5.2.5 on 2026-06-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_account_phone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['rider', 'origin', 'date'], name='trip_rider_origin_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['rider', 'destination', 'date'], name='trip_rider_dest_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['origin', 'date'], name='trip_origin_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['destination', 'date'], name='trip_dest_dt_idx'),
        ),
    ]
