# Generated by Django 5.2.5 on 2026-07-02 18:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trip_trip_rider_origin_dt_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('meter_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('waiting_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('riders', models.ManyToManyField(blank=True, related_name='service_plans', to='core.rider')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.zone')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waiting_min', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('unsettled', 'Unsettled'), ('settled', 'Settled')], default='unsettled', max_length=12)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='core.trip')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.serviceplan')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='service_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.serviceplan'),
        ),
        migrations.AddConstraint(
            model_name='serviceplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('zone',), name='one_default_plan_per_zone'),
        ),
        migrations.AddConstraint(
            model_name='serviceplan',
            constraint=models.UniqueConstraint(fields=('zone', 'name'), name='unique_plan_name_per_zone'),
        ),
    ]
