# Generated by Django 5.2.5 on 2026-07-03 09:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_default_zone_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=core.models._unassign_driver_on_delete, related_name='trips', to='core.driver'),
        ),
    ]
