# Generated by Django 5.2.5 on 2026-07-03 09:54

from django.db import migrations, models


def rename_scheduled_to_unassigned(apps, schema_editor):
    Trip = apps.get_model('core', 'Trip')
    Trip.objects.filter(status='scheduled').update(status='unassigned')


def rename_unassigned_to_scheduled(apps, schema_editor):
    Trip = apps.get_model('core', 'Trip')
    Trip.objects.filter(status='unassigned').update(status='scheduled')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_trip_driver'),
    ]

    operations = [
        migrations.RunPython(
            rename_scheduled_to_unassigned, rename_unassigned_to_scheduled
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('enroute', 'En Route'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='unassigned', max_length=20),
        ),
    ]
