# Generated by Django 5.2.5 on 2026-07-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vehicle_vehicledocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('unavailable', 'Unavailable'), ('available', 'Available')], default='unavailable', max_length=12),
        ),
    ]
